# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 6, 17, 5, 39, 38, 308837, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
